version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: app_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes
    networks:
      - app_network
volumes:
  redis_data:

networks:
  app_network:
    driver: bridge